version: "3"

vars:
  cluster: "infra2-cluster"

tasks:
  ecs-services:
    desc: List all running ECS services by name
    cmds:
      - aws ecs list-services --cluster {{.cluster }} | jq .serviceArns[] -r | awk -F '/' '{print $NF}'
