#cloud-config

repo_update: true

packages:
  - curl
  - jq

runcmd:
  - latest_version=$(curl -s https://api.github.com/repos/traefik/traefik/releases/latest | jq -r .tag_name)
  - curl -L https://github.com/traefik/traefik/releases/download/${latest_version}/traefik_${latest_version}_linux_amd64.tar.gz --output traefik.tar.gz

  - tar -zxvf traefik.tar.gz

  - sudo install -m 755 traefik /usr/local/bin/traefik
  - sudo setcap 'cap_net_bind_service=+ep' /usr/local/bin/traefik

  - sudo groupadd -g 321 traefik
  - sudo useradd -r -u 321 -g traefik -s /usr/sbin/nologin traefik

  - sudo mkdir -p /etc/traefik/acme /var/log/traefik
  - sudo chown -R traefik:traefik /etc/traefik/acme /var/log/traefik
